import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Main App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h2 className={styles.title}>
          Welcome to Main Application !
        </h2>

       
        <div className={styles.grid}>
          <a href="https://61a37221ba310a00082a4840--wizardly-jang-77eb50.netlify.app/" className={styles.card}>
            <h2>First Game &rarr;</h2>
            <p>Click to open first game!</p>
          </a>

          <a href="https://61a3725dcc1672c216e66244--ecstatic-joliot-8da632.netlify.app/" className={styles.card}>
            <h2>Second Game &rarr;</h2>
            <p>Click to open second game!</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
          Built by Gourish Vashisht
      </footer>
    </div>
  )
}
